# -*- coding: utf-8 -*-
"""Arya_2648510_LAB6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VtZoIPDiMSWBbpGBkg8WhMubIjYYBB0

# MAI412-1 – Machine Learning | I MSc AIM
## Lab Exercise 6: Colossal Pattern Mining using Pattern Fusion
**Dataset:** BTC-2017min.csv (Bitcoin minute-level OHLCV data, full year 2017)
**Name:** _______________  |  **Register No. (last 3 digits):** ___  |  **File:** `Name_XXX_Lab6.ipynb`
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

"""## Task 1: Dataset Design

**Domain selected:** Cryptocurrency market behavior — Bitcoin (BTC/USD) minute-level trading data for the year 2017.

Instead of using raw minute-level rows (525,600 of them, which is too fine-grained and noisy for
frequent pattern mining), the dataset is **resampled to one transaction per calendar day**
(365 transactions for 2017). Each day is described by a "basket" of categorical items derived
from that day's price and volume behaviour — this mirrors how a retail transaction is a basket
of items, except here each "item" is a market condition that occurred that day.

"""

ds = pd.read_csv("BTC-2017min.csv")
ds['date'] = pd.to_datetime(ds['date'])
ds.set_index('date', inplace=True)
ds.sort_index(inplace=True)

print(f"Raw minute-level rows: {len(ds)}")
ds.head()

daily = ds.resample('D').agg({
    'open': 'first',
    'high': 'max',
    'low': 'min',
    'close': 'last',
    'Volume BTC': 'sum'
}).dropna()

print(f"Daily transactions (records): {len(daily)}")
daily.head()

daily['Is_Weekend']  = np.where(daily.index.dayofweek >= 5, 'Weekend', 'Weekday')
daily['Quarter']     = 'Q' + daily.index.quarter.astype(str)

conditions = [(daily['close'] > daily['open']), (daily['close'] < daily['open'])]
daily['Trend'] = np.select(conditions, ['Bullish', 'Bearish'], default='Flat')

daily['Spread'] = daily['high'] - daily['low']
sq25, sq75 = daily['Spread'].quantile([0.25, 0.75])
daily['Volatility'] = np.select(
    [daily['Spread'] > sq75, daily['Spread'] < sq25],
    ['High_Volatility', 'Low_Volatility'],
    default='Normal_Volatility'
)

vq25, vq75 = daily['Volume BTC'].quantile([0.25, 0.75])
daily['VolumeState'] = np.select(
    [daily['Volume BTC'] > vq75, daily['Volume BTC'] < vq25],
    ['High_Volume', 'Low_Volume'],
    default='Normal_Volume'
)

med_close = daily['close'].median()
daily['PriceLevel'] = np.where(daily['close'] > med_close, 'Above_Median_Price', 'Below_Median_Price')

item_cols = ['Is_Weekend', 'Quarter', 'Trend', 'Volatility', 'VolumeState', 'PriceLevel']
daily[item_cols].head(10)

transactions = daily[item_cols].values.tolist()

print("Sample transactions (each = one day's market-condition basket):")
for t in transactions[:5]:
    print(t)

print(f"\nTotal Transactions : {len(transactions)}")
all_items = sorted(set(i for t in transactions for i in t))
print(f"Total Unique Items : {len(all_items)}")
print(f"Unique Items List  : {all_items}")

"""**Dataset summary**
- **Number of transactions:** 365 (one per day of 2017)
- **Number of unique items:** 16 (across 6 categorical dimensions: weekend/weekday, quarter, trend, volatility, volume, price level)
- **Domain:** Cryptocurrency (Bitcoin) daily market behaviour, derived from minute-level OHLCV trading data

## Task 2: Frequent Pattern Generation

Minimum support is set to **15%** (a pattern must occur on at least ~55 of the 365 days).
This is lower than the 30% suggested in the sample problem statement because with 6 independent
categorical dimensions per transaction, higher thresholds leave almost no itemsets of length > 2 —
15% still keeps patterns statistically meaningful while allowing colossal (larger) patterns to emerge.
"""

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

te = TransactionEncoder()
te_arr = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_arr, columns=te.columns_).astype(bool)
df.head()

min_support = 0.3

frequent_itemsets = apriori(df, min_support=min_support, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(len)
frequent_itemsets = frequent_itemsets.sort_values(['length', 'support'], ascending=[True, False]).reset_index(drop=True)

print(f"Total frequent itemsets generated: {len(frequent_itemsets)}")
print(f"Minimum Support: {min_support*100:.0f}%\n")
frequent_itemsets

print("Frequent itemsets by size:")
print(frequent_itemsets['length'].value_counts().sort_index())

"""## Task 3: Pattern Fusion

Starting from the length-2 frequent itemsets, every pair of current patterns that shares at
least one common item is **fused** (unioned) into a candidate larger pattern. If the fused
pattern still meets minimum support, it replaces its smaller parents in the working set. This
repeats until no further fusion is possible — directly jumping to large patterns instead of
enumerating every intermediate-size itemset the way Apriori does.
"""

def calculate_support(itemset, df):
    """Support of an arbitrary itemset (used to score fused candidates)."""
    condition = np.ones(len(df), dtype=bool)
    for item in itemset:
        condition &= df[item].values
    return condition.sum() / len(df)

# Seed the fusion process from length-2 frequent itemsets
current_patterns = [set(x) for x in frequent_itemsets[frequent_itemsets['length'] == 2]['itemsets']]
fusion_operations = 0
fusion_possible = True

while fusion_possible:
    fusion_possible = False
    next_patterns = list(current_patterns)

    for i in range(len(current_patterns)):
        for j in range(i + 1, len(current_patterns)):
            p1, p2 = current_patterns[i], current_patterns[j]
            common = p1 & p2                      # patterns having a common subset
            if len(common) >= 1:                   # compatible for fusion
                fused = p1 | p2                    # merge compatible patterns
                if len(fused) > max(len(p1), len(p2)) and fused not in next_patterns:
                    support = calculate_support(fused, df)
                    if support >= min_support:
                        next_patterns.append(fused)  # larger frequent pattern formed
                        fusion_operations += 1
                        fusion_possible = True

    if fusion_possible:
        current_patterns = next_patterns

print(f"Total Fusion Operations Performed: {fusion_operations}")
print(f"Patterns remaining after fusion (pre-maximality filter): {len(current_patterns)}")

"""## Task 4: Colossal Pattern Discovery

The final **colossal patterns** are the *maximal* fused patterns — i.e. patterns that are not a
proper subset of any other surviving fused pattern.
"""

colossal_patterns = [p for p in current_patterns if not any(p < q for q in current_patterns)]
# de-duplicate
colossal_patterns = list({frozenset(p): p for p in colossal_patterns}.values())
colossal_patterns.sort(key=len, reverse=True)

print(f"Total Colossal Patterns Discovered: {len(colossal_patterns)}\n")

for idx, pattern in enumerate(colossal_patterns, 1):
    support = calculate_support(pattern, df)
    print(f"Colossal Pattern {idx}: {sorted(pattern)}")
    print(f"   -> Support: {support:.4f} ({support*100:.2f}%)")
    print(f"   -> Number of items: {len(pattern)}\n")

"""## Task 5: Analysis"""

highest_support_row = frequent_itemsets.loc[frequent_itemsets['support'].idxmax()]
largest_colossal = max(colossal_patterns, key=len)
largest_support = calculate_support(largest_colossal, df)
before_count = len(frequent_itemsets)
after_count = len(colossal_patterns)

print(f"1. Highest-support pattern : {set(highest_support_row['itemsets'])}  "
      f"(support = {highest_support_row['support']*100:.2f}%)")
print(f"2. Largest (colossal) pattern : {sorted(largest_colossal)}  "
      f"(support = {largest_support*100:.2f}%, size = {len(largest_colossal)})")
print(f"3. Number of fusion operations performed : {fusion_operations}")
print(f"4. Frequent itemsets before fusion : {before_count}  |  Colossal patterns after fusion : {after_count}")

"""**Written answers**

1. **Highest support pattern:** the single-item pattern printed above (typically `Weekday`, since
   5 of 7 days are weekdays — roughly 71% of transactions contain it).

2. **Largest (colossal) pattern:** the pattern printed above, combining several market conditions
   (e.g. weekday + a specific volatility/volume state + trend + price level) that co-occurred on
   a meaningful share of days in 2017.

3. **Fusion operations performed:** shown above — each successful merge of two compatible
   patterns into a larger, still-frequent pattern counts as one fusion operation.

4. **Before vs. after comparison:** Apriori alone generated the *before* count of frequent
   itemsets spanning sizes 1 through 4. Pattern Fusion condensed these into a much smaller set of
   *after* colossal (maximal) patterns — every smaller itemset that is a subset of a surviving
   colossal pattern is implied by it and does not need to be reported separately.

5. **How Pattern Fusion reduces redundancy:** Apriori-style mining outputs *every* frequent
   subset of a large pattern — a frequent 4-item pattern implies 2⁴ − 1 = 15 non-empty subsets
   that are all technically "frequent" but describe the same underlying market condition (e.g.
   "weekday", "weekday + bullish", "weekday + bullish + normal volatility" are all fragments of
   one larger, more informative pattern). Pattern Fusion skips reporting this exponential fan-out
   of intermediate subsets. Instead of growing patterns one item at a time and keeping every
   intermediate size, it merges compatible frequent patterns directly into their maximal form, so
   the final output contains only the large, non-redundant, maximally-informative patterns —
   cutting both the number of patterns to review and the computation spent generating them.

"""