# -*- coding: utf-8 -*-
"""Arya_2648510_LAB5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTdj5xNZpUbN45RXwWcPas8btbNyfGN3
"""

import warnings
warnings.filterwarnings('ignore')

ds = pd.read_csv("./BTC-2017min.csv")

if 'unix' in ds.columns:
    ds['date'] = pd.to_datetime(ds['unix'], unit='s')
    ds.set_index('date', inplace=True)

ds['Day_of_Week'] = ds.index.day_name()
ds['Is_Weekend'] = ds.index.dayofweek >= 5
ds['Month'] = ds.index.month_name()


conditions = [
    (ds['close'] > ds['open']),
    (ds['close'] < ds['open'])
]
ds['Daily_Trend'] = np.select(conditions, ['Bullish', 'Bearish'], default='Flat')

ds['Spread'] = ds['high'] - ds['low']
q25 = ds['Spread'].quantile(0.25)
q75 = ds['Spread'].quantile(0.75)
ds['Volatility_State'] = np.select(
    [(ds['Spread'] > q75), (ds['Spread'] < q25)],
    ['High', 'Low'],
    default='Normal'
)


print(ds.head())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
fig = plt.figure(figsize=(18, 11))
fig.suptitle("OLAP Operations on BTC CSV Dataset)", fontsize=18, weight='bold', y=0.98)

day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
trend_order = ['Bullish', 'Bearish', 'Flat']
vol_order = ['Low', 'Normal', 'High']


ax1 = fig.add_subplot(2, 3, 1, projection='3d')
cuboid_data = ds.groupby(['Daily_Trend', 'Volatility_State'])['Spread'].mean().unstack()

x_labels, y_labels = trend_order, vol_order
x, y = np.meshgrid(np.arange(len(x_labels)), np.arange(len(y_labels)))
x, y = x.flatten(), y.flatten()
z = np.zeros_like(x)
dx = dy = 0.5

dz_values = []
for y_idx, y_val in enumerate(y_labels):
    for x_idx, x_val in enumerate(x_labels):
        dz_values.append(cuboid_data.loc[x_val, y_val] if (x_val in cuboid_data.index and y_val in cuboid_data.columns) else 0)

colors = ['#2b7bba', '#4cb140', '#e54035'] * len(y_labels)
ax1.bar3d(x, y, z, dx, dy, dz_values, color=colors, alpha=0.85, shade=True)

ax1.set_xticks(np.arange(len(x_labels)) + 0.25)
ax1.set_xticklabels(x_labels, rotation=-15, fontsize=8)
ax1.set_yticks(np.arange(len(y_labels)) + 0.25)
ax1.set_yticklabels(y_labels, rotation=30, fontsize=8)
ax1.set_zlabel('Avg Spread ($)', weight='bold')
ax1.set_title("1. 3D OLAP CUBOID\n(Trend × Volatility × Avg Spread)", weight='bold', color='#002b66')

ax2 = fig.add_subplot(2, 3, 2)
rollup_df = ds.groupby('Month')['Spread'].mean().reset_index()
sns.barplot(data=rollup_df, x='Month', y='Spread', color='#2b7bba', ax=ax2)
ax2.bar_label(ax2.containers[0], fmt='%.2f', padding=3, weight='bold')
ax2.set_title("2. ROLL-UP\n(Higher Granularity: Month-wise Spread)", weight='bold', color='#002b66')
ax2.set_ylabel("Avg Spread ($)", weight='bold')
ax2.tick_params(axis='x', rotation=30)


ax3 = fig.add_subplot(2, 3, 3)
drill_df = ds.groupby('Day_of_Week')['Spread'].mean().reindex(day_order).reset_index()
sns.barplot(data=drill_df, x='Day_of_Week', y='Spread', palette='viridis', ax=ax3)
ax3.bar_label(ax3.containers[0], fmt='%.2f', padding=3, weight='bold')
ax3.set_title("3. DRILL-DOWN\n(Lower Granularity: Day of Week Spread)", weight='bold', color='#002b66')
ax3.set_ylabel("Avg Spread ($)", weight='bold')
ax3.tick_params(axis='x', rotation=30)


ax4 = fig.add_subplot(2, 3, 4)
slice_df = ds[ds['Daily_Trend'] == 'Bullish'].pivot_table(
    index='Day_of_Week', columns='Month', values='Spread', aggfunc='mean'
).reindex(day_order)

sns.heatmap(slice_df, annot=True, fmt=".1f", cmap="YlGnBu", cbar_kws={'label': 'Avg Spread', 'orientation': 'horizontal', 'pad': 0.15}, ax=ax4, linewidths=0.5)
ax4.set_title("4. SLICE\n(Filter: Daily_Trend = Bullish)", weight='bold', color='#002b66')


ax5 = fig.add_subplot(2, 3, 5)
diced_ds = ds[
    (ds['Volatility_State'].isin(['High', 'Low'])) &
    (ds['Daily_Trend'].isin(['Bullish', 'Bearish']))
]
dice_df = diced_ds.pivot_table(
    index=['Volatility_State', 'Daily_Trend'],
    columns='Day_of_Week',
    values='Spread',
    aggfunc='mean'
)[day_order]

sns.heatmap(dice_df, annot=True, fmt=".1f", cmap="YlOrRd", cbar_kws={'label': 'Avg Spread', 'orientation': 'horizontal', 'pad': 0.15}, ax=ax5, linewidths=0.5)
ax5.set_title("5. DICE\n(Sub-cube: High/Low Volatility & Bull/Bear)", weight='bold', color='#002b66')


ax6 = fig.add_subplot(2, 3, 6)
ax6.axis('off')

pivot_table = pd.pivot_table(
    ds,
    values='Spread',
    index='Daily_Trend',
    columns='Volatility_State',
    aggfunc='mean',
    margins=True,
    margins_name='Total'
).round(2).reindex(index=['Bullish', 'Bearish', 'Flat', 'Total'], columns=['Low', 'Normal', 'High', 'Total'])

table = ax6.table(
    cellText=pivot_table.values,
    rowLabels=pivot_table.index,
    colLabels=pivot_table.columns,
    cellLoc='center',
    loc='center'
)
table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 1.8)

for (row, col), cell in table.get_celld().items():
    if row == 0 or col == -1 or row == len(pivot_table):
        cell.set_facecolor('#d9e8f5')
        cell.set_text_props(weight='bold')
    else:
        cell.set_facecolor('#ffffff')

ax6.set_title("6. PIVOT TABLE\n(Rotate: Trend as Rows, Volatility as Columns)", weight='bold', color='#002b66', pad=20)

plt.tight_layout()
plt.subplots_adjust(top=0.90, hspace=0.35, wspace=0.25)
plt.show()

vol_col = 'Volume USD' if 'Volume USD' in ds.columns else ('Volume BTC' if 'Volume BTC' in ds.columns else None)

if vol_col:
    ds['Volume_Level'] = pd.qcut(ds[vol_col], q=3, labels=['Low_Vol', 'Med_Vol', 'High_Vol'])


feature_cols = ['Day_of_Week', 'Is_Weekend', 'Month', 'Daily_Trend', 'Volatility_State']
if vol_col:
    feature_cols.append('Volume_Level')

mining_df = ds[feature_cols].copy()
mining_df['Is_Weekend'] = mining_df['Is_Weekend'].astype(str)

basket_df = pd.get_dummies(mining_df, prefix_sep=': ').astype(bool)

frequent_itemsets = apriori(basket_df, min_support=0.05, use_colnames=True)

confidence = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
support = association_rules(frequent_itemsets, metric="support", min_threshold=0.7)
lift = association_rules(frequent_itemsets, metric="lift", min_threshold=0.7)


sorted_rules = market_rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values(
    by='lift', ascending=False
)

print("\n top associations")
print(sorted_rules.to_string(index=False))

import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

ds = pd.read_csv("./BTC-2017min.csv").head(25)
ds['date'] = pd.to_datetime(ds['unix'], unit='s')
ds.set_index('date', inplace=True)

ds['Day_of_Week'] = ds.index.day_name()
ds['Is_Weekend'] = (ds.index.dayofweek >= 5).astype(str)
ds['Month'] = ds.index.month_name()

ds['Daily_Trend'] = np.sign(ds['close'] - ds['open']).map({1: 'Bullish', -1: 'Bearish', 0: 'Flat'})

ds['Volatility_State'] = pd.qcut(
    ds['high'] - ds['low'],
    q=[0, 0.25, 0.75, 1.0],
    labels=['Low', 'Normal', 'High'],
    duplicates='drop'
)

cols = ['Day_of_Week', 'Is_Weekend', 'Month', 'Daily_Trend', 'Volatility_State']

ds[cols]

basket_df = pd.get_dummies(ds[cols], prefix_sep=': ').astype(bool)

basket_df

from mlxtend.frequent_patterns import apriori, association_rules


frequent_itemsets = apriori(basket_df, min_support=0.08, use_colnames=True)


rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)


if not rules.empty:
    rules['target'] = rules['consequents'].apply(lambda x: ', '.join(x))
    market_rules = rules[rules['target'].str.contains('Daily_Trend|Volatility_State')].sort_values('lift', ascending=False)


    display(market_rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])
else:
    print("No rules met the support and confidence threshold on this 25-row slice.")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns


sns.set_theme(style="whitegrid")
fig = plt.figure(figsize=(18, 11))
fig.suptitle(
    "OLAP Operations on 25 Records (5 Categorical Dimensions)",
    fontsize=18,
    weight="bold",
    y=0.98,
)

#3d olap
ax1 = fig.add_subplot(2, 3, 1, projection="3d")
cuboid_data = pd.crosstab(ds["Daily_Trend"], ds["Volatility_State"])

x_labels = cuboid_data.index.tolist()
y_labels = cuboid_data.columns.tolist()

if len(x_labels) > 0 and len(y_labels) > 0:
  x, y = np.meshgrid(np.arange(len(x_labels)), np.arange(len(y_labels)))
  x, y = x.flatten(), y.flatten()
  z = np.zeros_like(x)
  dx = dy = 0.5
  dz = cuboid_data.values.T.flatten()

  colors = ["#2b7bba", "#4cb140", "#e54035", "#f4c12c"] * len(y_labels)
  ax1.bar3d(
      x, y, z, dx, dy, dz, color=colors[: len(dz)], alpha=0.85, shade=True
  )

  ax1.set_xticks(np.arange(len(x_labels)) + 0.25)
  ax1.set_xticklabels(x_labels, rotation=-15, fontsize=8)
  ax1.set_yticks(np.arange(len(y_labels)) + 0.25)
  ax1.set_yticklabels(y_labels, rotation=30, fontsize=8)
  ax1.set_zlabel("Record Count", weight="bold")

ax1.set_title(
    "1. 3D OLAP CUBOID\n(Trend × Volatility × Count)",
    weight="bold",
    color="#002b66",
)

#roll up
ax2 = fig.add_subplot(2, 3, 2)
rollup_df = ds["Is_Weekend"].value_counts().reset_index()
rollup_df.columns = ["Is_Weekend", "Count"]

sns.barplot(
    data=rollup_df, x="Is_Weekend", y="Count", palette=["#2b7bba"], ax=ax2
)
ax2.bar_label(ax2.containers[0], padding=3, weight="bold")
ax2.set_title(
    "2. ROLL-UP\n(Higher Level: Is_Weekend Summary)",
    weight="bold",
    color="#002b66",
)
ax2.set_ylabel("Record Count", weight="bold")

#drill-down
ax3 = fig.add_subplot(2, 3, 3)
drill_df = ds["Volatility_State"].value_counts().reset_index()
drill_df.columns = ["Volatility_State", "Count"]

sns.barplot(
    data=drill_df, x="Volatility_State", y="Count", palette="viridis", ax=ax3
)
ax3.bar_label(ax3.containers[0], padding=3, weight="bold")
ax3.set_title(
    "3. DRILL-DOWN\n(Detailed Level: Volatility_State)",
    weight="bold",
    color="#002b66",
)
ax3.set_ylabel("Record Count", weight="bold")

#slice
ax4 = fig.add_subplot(2, 3, 4)
slice_data = ds[ds["Daily_Trend"] == "Bullish"]
slice_df = pd.crosstab(slice_data["Day_of_Week"], slice_data["Volatility_State"])


if slice_df.empty:
  slice_df = pd.crosstab(ds["Day_of_Week"], ds["Volatility_State"])

sns.heatmap(
    slice_df,
    annot=True,
    fmt="d",
    cmap="YlGnBu",
    cbar=False,
    ax=ax4,
    linewidths=0.5,
)
ax4.set_title(
    "4. SLICE\n(Filter: Daily_Trend = Bullish)", weight="bold", color="#002b66"
)

#dice
ax5 = fig.add_subplot(2, 3, 5)
dice_df = pd.crosstab(ds["Daily_Trend"], ds["Volatility_State"])

sns.heatmap(
    dice_df,
    annot=True,
    fmt="d",
    cmap="YlOrRd",
    cbar=False,
    ax=ax5,
    linewidths=0.5,
)
ax5.set_title(
    "5. DICE\n(Sub-cube: Trend × Volatility Matrix)",
    weight="bold",
    color="#002b66",
)

#pivot
ax6 = fig.add_subplot(2, 3, 6)
ax6.axis("off")

pivot_table = pd.crosstab(
    ds["Daily_Trend"],
    ds["Volatility_State"],
    margins=True,
    margins_name="Total",
)

table = ax6.table(
    cellText=pivot_table.values,
    rowLabels=pivot_table.index,
    colLabels=pivot_table.columns,
    cellLoc="center",
    loc="center",
)
table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 1.8)

# Format table styling to highlight headers & totals
for (row, col), cell in table.get_celld().items():
  if row == 0 or col == -1 or row == len(pivot_table):
    cell.set_facecolor("#d9e8f5")
    cell.set_text_props(weight="bold")
  else:
    cell.set_facecolor("#ffffff")

ax6.set_title(
    "6. PIVOT TABLE\n(Rotate: Trend as Rows, Volatility as Columns)",
    weight="bold",
    color="#002b66",
    pad=20,
)

plt.tight_layout()
plt.subplots_adjust(top=0.90, hspace=0.35, wspace=0.25)
plt.show()

