# -*- coding: utf-8 -*-
"""Arya_2648510_Lab 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFgdSmP6dj4h6AbQI5d0gQQKrMIFelWj
"""

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# 1. Define the Dataset
# Recreating the 6 prescription records from your image
dataset = [
    ['Paracetamol', 'Vitamin C', 'Cough Syrup'],
    ['Paracetamol', 'Antibiotic', 'Vitamin C'],
    ['Antibiotic', 'Vitamin C', 'Pain Reliever'],
    ['Paracetamol', 'Vitamin C', 'Pain Reliever'],
    ['Paracetamol', 'Antibiotic', 'Vitamin C'],
    ['Vitamin C', 'Cough Syrup']
]

# 2. Preprocess the Data (One-Hot Encoding)
# The Apriori algorithm in mlxtend requires the data to be in a boolean format
# where columns are items and rows represent whether the item was in the transaction (True/False).
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

print("--- Transaction Database (One-Hot Encoded) ---")
print(df.head())
print("\n")

# 3. Apply the Apriori Algorithm
# The minimum support count is 3 out of 6 transactions, so min_support = 3/6 = 0.5
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)

print("--- Frequent Itemsets ---")
print(frequent_itemsets)
print("\n")

# 4. Generate Association Rules
# We use the frequent itemsets to generate rules.
# We'll set a minimum confidence threshold of 50% (0.5) to see our results.
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

# For clarity, let's only print the most relevant columns
print("--- Association Rules (Support, Confidence, Lift) ---")
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

import itertools

# 1. Define the Dataset
dataset = [
    ['Paracetamol', 'Vitamin C', 'Cough Syrup'],
    ['Paracetamol', 'Antibiotic', 'Vitamin C'],
    ['Antibiotic', 'Vitamin C', 'Pain Reliever'],
    ['Paracetamol', 'Vitamin C', 'Pain Reliever'],
    ['Paracetamol', 'Antibiotic', 'Vitamin C'],
    ['Vitamin C', 'Cough Syrup','Dolo']
]

min_support_count = 3
transactions = [set(t) for t in dataset]

def get_support_count(itemset):
    """Counts how many transactions contain the itemset."""
    return sum(1 for t in transactions if itemset.issubset(t))

def apriori_with_logs():
    print(f"--- INITIAL PARAMETERS ---")
    print(f"Total Transactions: {len(transactions)}")
    print(f"Minimum Support Count: {min_support_count}\n")

    print("=== ITERATION 1 ===")
    unique_items = set(item for t in dataset for item in t)
    C1 = [frozenset([item]) for item in unique_items]

    L1 = []
    pruned_1 = []

    for candidate in C1:
        count = get_support_count(candidate)
        if count >= min_support_count:
            L1.append(candidate)
        else:
            pruned_1.append((candidate, count))

    print(f"Kept (L1): {[set(x) for x in L1]}")
    print(f"Pruned (Low Support): {[set(x[0]) for x in pruned_1]}\n")

    current_L = L1
    k = 2

    while current_L:
        print(f"=== ITERATION {k} ===")

        Ck = set()
        for itemset1 in current_L:
            for itemset2 in current_L:
                new_itemset = itemset1.union(itemset2)
                if len(new_itemset) == k:
                    Ck.add(new_itemset)

        if not Ck:
            print("No more candidates can be generated. Algorithm terminates.")
            break

        apriori_pruned = []
        valid_candidates = []

        for candidate in Ck:
            subsets = [frozenset(x) for x in itertools.combinations(candidate, k-1)]
            if all(subset in current_L for subset in subsets):
                valid_candidates.append(candidate)
            else:
                apriori_pruned.append(candidate)

        print(f"Generated Candidates (C{k}): {[set(x) for x in Ck]}")
        if apriori_pruned:
            print(f"Pruned (Apriori Principle - Subset not frequent): {[set(x) for x in apriori_pruned]}")

        next_L = []
        support_pruned = []

        for candidate in valid_candidates:
            count = get_support_count(candidate)
            if count >= min_support_count:
                next_L.append(candidate)
            else:
                support_pruned.append((candidate, count))

        if support_pruned:
            print(f"Pruned (Low Support): {[set(x[0]) for x in support_pruned]}")

        print(f"Kept (L{k}): {[set(x) for x in next_L]}\n")

        current_L = next_L
        k += 1

# Run the algorithm
apriori_with_logs()

import itertools

dataset = [
    ['Paracetamol', 'Vitamin C', 'Cough Syrup'],
    ['Paracetamol', 'Antibiotic', 'Vitamin C'],
    ['Antibiotic', 'Vitamin C', 'Pain Reliever'],
    ['Paracetamol', 'Vitamin C', 'Pain Reliever'],
    ['Paracetamol', 'Antibiotic', 'Vitamin C'],
    ['Vitamin C', 'Cough Syrup']
]

# Convert transactions to sets for easier subset checking
transactions = [set(transaction) for transaction in dataset]
min_support_count = 3

def get_support(itemset, transactions):
    """Calculates the support count of an itemset in the transactions."""
    return sum(1 for transaction in transactions if itemset.issubset(transaction))

print(" Minimum Support Count:", min_support_count)

# Extract all unique items
unique_items = set(item for transaction in dataset for item in transaction)
C1 = {frozenset([item]): get_support(frozenset([item]), transactions) for item in unique_items}

print("--- Candidate 1-Itemsets (C1) ---")
for itemset, count in C1.items():
    print(f"{set(itemset)}: {count}")

L1 = {itemset: count for itemset, count in C1.items() if count >= min_support_count}

print("\n--- Frequent 1-Itemsets (L1) ---")
for itemset, count in L1.items():
    print(f"{set(itemset)}: {count}")

pruned_1 = set(C1.keys()) - set(L1.keys())
print(f"\nPruned (Support < 3): {[set(i) for i in pruned_1]}")

# Task 1: Generate Candidate 2-Itemsets (C2) using items from L1
L1_items = list(L1.keys())
C2_candidates = set()

for i in range(len(L1_items)):
    for j in range(i + 1, len(L1_items)):
        C2_candidates.add(L1_items[i].union(L1_items[j]))

C2 = {itemset: get_support(itemset, transactions) for itemset in C2_candidates}

print("--- Candidate 2-Itemsets (C2) ---")
for itemset, count in C2.items():
    print(f"{set(itemset)}: {count}")

L2 = {itemset: count for itemset, count in C2.items() if count >= min_support_count}

print("\n--- Frequent 2-Itemsets (L2) ---")
for itemset, count in L2.items():
    print(f"{set(itemset)}: {count}")

pruned_2 = set(C2.keys()) - set(L2.keys())
print(f"\nPruned (Support < 3): {[set(i) for i in pruned_2]}")

# Task 1: Generate Candidate 3-Itemsets (C3)
L2_items = list(L2.keys())
C3_potential = set()

for i in range(len(L2_items)):
    for j in range(i + 1, len(L2_items)):
        union_set = L2_items[i].union(L2_items[j])
        if len(union_set) == 3:
            C3_potential.add(union_set)

print("--- Potential 3-Itemsets Generated ---")
print([set(i) for i in C3_potential])


C3_valid = set()
apriori_pruned = []

for candidate in C3_potential:
    subsets = [frozenset(x) for x in itertools.combinations(candidate, 2)]

    if all(subset in L2 for subset in subsets):
        C3_valid.add(candidate)
    else:
        apriori_pruned.append(candidate)

print("\n--- Task 3: Apriori Pruning Applied ---")
if apriori_pruned:
    print(f"Pruned Itemsets (Subsets not in L2): {[set(i) for i in apriori_pruned]}")
    print("Reasoning: 'Paracetamol' and 'Antibiotic' are not frequently prescribed together (Support < 3), therefore the larger set cannot be frequent.")

C3 = {itemset: get_support(itemset, transactions) for itemset in C3_valid}
L3 = {itemset: count for itemset, count in C3.items() if count >= min_support_count}

print("\n--- Candidate 3-Itemsets (C3) ---")
print("Empty" if not C3 else C3)

print("\n--- Frequent 3-Itemsets (L3) ---")
print("Empty" if not L3 else L3)



"""####Q2"""

import itertools

# Define the dataset from the library borrowing records
dataset = [
    ['Data Structures', 'Python Programming', 'DBMS'],
    ['Data Structures', 'Operating Systems'],
    ['Python Programming', 'DBMS', 'Machine Learning'],
    ['Data Structures', 'Python Programming', 'Machine Learning'],
    ['Data Structures', 'Python Programming', 'DBMS'],
    ['Python Programming', 'DBMS']
]

# Convert each transaction list to a set for faster Apriori subset operations
transactions = [set(transaction) for transaction in dataset]
min_support_count = 3

def get_support(itemset, transactions):
    """Calculates how many times an itemset appears in the transaction database."""
    return sum(1 for transaction in transactions if itemset.issubset(transaction))

print("Library Dataset loaded.")
print(f"Total Transactions: {len(transactions)}")
print(f"Minimum Support Count: {min_support_count}")

unique_books = set(item for transaction in dataset for item in transaction)

C1 = {frozenset([book]): get_support(frozenset([book]), transactions) for book in unique_books}

print("--- Candidate 1-Itemsets (C1) ---")
for itemset, count in sorted(C1.items(), key=lambda x: x[1], reverse=True):
    print(f"{set(itemset)}: {count}")

L1 = {itemset: count for itemset, count in C1.items() if count >= min_support_count}

print("\n--- Frequent 1-Itemsets (L1) ---")
for itemset, count in sorted(L1.items(), key=lambda x: x[1], reverse=True):
    print(f"{set(itemset)}: {count}")

L1_items = list(L1.keys())
C2_candidates = set()

for i in range(len(L1_items)):
    for j in range(i + 1, len(L1_items)):
        C2_candidates.add(L1_items[i].union(L1_items[j]))

C2 = {itemset: get_support(itemset, transactions) for itemset in C2_candidates}

print("--- Candidate 2-Itemsets (C2) ---")
for itemset, count in sorted(C2.items(), key=lambda x: x[1], reverse=True):
    print(f"{set(itemset)}: {count}")

L2 = {itemset: count for itemset, count in C2.items() if count >= min_support_count}

print("\n--- Frequent 2-Itemsets (L2) ---")
for itemset, count in sorted(L2.items(), key=lambda x: x[1], reverse=True):
    print(f"{set(itemset)}: {count}")

L2_items = list(L2.keys())
C3_potential = set()

for i in range(len(L2_items)):
    for j in range(i + 1, len(L2_items)):
        union_set = L2_items[i].union(L2_items[j])
        if len(union_set) == 3:
            C3_potential.add(union_set)

print(f"Potential 3-Itemsets from Join: {[set(i) for i in C3_potential]}\n")

C3_valid = set()
pruned_sets = []

for candidate in C3_potential:
    subsets = [frozenset(x) for x in itertools.combinations(candidate, 2)]

    if all(subset in L2 for subset in subsets):
        C3_valid.add(candidate)
    else:
        pruned_sets.append(candidate)

print("--- Apriori Pruning Applied ---")
for pruned in pruned_sets:
    print(f"Pruned Itemset: {set(pruned)}")
    print("Reason: Not all of its 2-book subsets are frequent (e.g., Data Structures & DBMS are rarely borrowed together).")

C3 = {itemset: get_support(itemset, transactions) for itemset in C3_valid}
print(f"\nFinal Valid Candidate 3-Itemsets (C3): {C3 if C3 else 'Empty'}")