# -*- coding: utf-8 -*-
"""Arya_2648510_LAB3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DjUX-Cr9peM6pVr6xF1tMeAGfxhikB7
"""

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

dataset = [
    ['Action', 'Comedy', 'Thriller'],
    ['Action', 'Drama', 'Thriller'],
    ['Comedy', 'Thriller', 'Romance'],
    ['Action', 'Comedy', 'Thriller'],
    ['Action', 'Comedy', 'Drama']
]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = fpgrowth(df, min_support=0.6, use_colnames=True)
print(frequent_itemsets)





import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

dataset = [
    ['Smart Light', 'Smart TV', 'Air Conditioner'],
    ['Smart Light', 'Smart Speaker', 'Air Conditioner'],
    ['Smart TV', 'Air Conditioner', 'Smart Speaker'],
    ['Smart Light', 'Smart TV', 'Air Conditioner'],
    ['Smart Light', 'Air Conditioner', 'Smart Speaker']
]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = fpgrowth(df, min_support=0.6, use_colnames=True)
print(frequent_itemsets)